services:
  - type: web
    name: raju-agent
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: GOOGLE_GENAI_USE_VERTEXAI
        value: "False"
      - key: GOOGLE_API_KEY
        sync: false # Render will prompt you for this value
